// Hand-drawn Chapter I creatures added in 2.0: the Paper Lurker, Mildew, the Lampkeeper and the
// Old Trunk (preview: npx tsx tests/sprite-png.ts src/art/hand/cellar2.ts out.png).
import type { Palette } from '../grid';

export const TRUNK_PAL: Palette = { o: '#1a100a', w: '#5a3a22', W: '#7e5634', h: '#a87a4a', b: '#2c2a2e', B: '#5e5a62', s: '#9a96a0', g: '#c8a050', m: '#2a0a10', r: '#a02a34', t: '#e8dcc0', y: '#ffd040' };
export const LURK_PAL: Palette = { o: '#1e1810', p: '#d8ccb0', P: '#efe6cc', q: '#a89a7a', k: '#3a3026', e: '#ff4a3a', E: '#ffd0b0', t: '#f4f0e0' };
export const MILDEW_PAL: Palette = { o: '#101a0c', c: '#2e4a22', C: '#4e7a32', h: '#8ac060', s: '#c8d8a0', t: '#d8d0b0', T: '#a8a080', g: '#c8ff70' };
export const KEEPER_PAL: Palette = { o: '#120c10', c: '#2a1e38', C: '#4a3a62', h: '#7a62a0', k: '#0a0608', e: '#ffe080', L: '#ffc040', y: '#fff4c0' };
export const TRUNK_FRAMES: string[][] = [[
    '......................',
    '..oooooooooooooooooo..',
    '.oWhhhhhhhhhhhhhhhhWo.',
    'oWhWWWWWWWWWWWWWWWWhWo',
    'obBsBBBBBBBBBBBBBBsBbo',
    'oWWWWWWWWWWWWWWWWWWWWo',
    'ooooooooooggoooooooooo',
    'owWWWWWWWWggWWWWWWWWwo',
    'oWWhWWWWWWWWWWWWWWhWWo',
    'obBsBBBBBBBBBBBBBBsBbo',
    'oWWWWWWWWWWWWWWWWWWWWo',
    'oWWWWWWWWWWWWWWWWWWWWo',
    'owWWWWWWWWWWWWWWWWWWwo',
    'obBBBBBBBBBBBBBBBBBBbo',
    '.oooooooooooooooooooo.',
    '..ob..............bo..',
  ], [
    '..oooooooooooooooooo..',
    '.oWhhhhhhhhhhhhhhhhWo.',
    'oWhWWWWWWWWWWWWWWWWhWo',
    'obBsBBBBBBBBBBBBBBsBbo',
    'oWWWWWWWWWWWWWWWWWWWWo',
    'ooooooooooggoooooooooo',
    'omtmmmtmmmyymmmtmmmtmo',
    'owWWWWWWWWggWWWWWWWWwo',
    'oWWhWWWWWWWWWWWWWWhWWo',
    'obBsBBBBBBBBBBBBBBsBbo',
    'oWWWWWWWWWWWWWWWWWWWWo',
    'oWWWWWWWWWWWWWWWWWWWWo',
    'owWWWWWWWWWWWWWWWWWWwo',
    'obBBBBBBBBBBBBBBBBBBbo',
    '.oooooooooooooooooooo.',
    '..ob..............bo..',
  ], [
    '..oooooooooooooooooo..',
    '.oWhhhhhhhhhhhhhhhhWo.',
    'obBsBBBBBBBBBBBBBBsBbo',
    'ooooooooooggoooooooooo',
    'otttmtttmttttmtttmttto',
    'ommmmmmmmmyymmmmmmmmmo',
    'ommmmmmmrrrrrrmmmmmmmo',
    'ommmmmrrrrrrrrrrmmmmmo',
    'otmttmttmttttmttmttmto',
    'obBsBBBBBBBBBBBBBBsBbo',
    'oWWWWWWWWWWWWWWWWWWWWo',
    'oWWWWWWWWWWWWWWWWWWWWo',
    'owWWWWWWWWWWWWWWWWWWwo',
    'obBBBBBBBBBBBBBBBBBBbo',
    '.oooooooooooooooooooo.',
    '..ob..............bo..',
  ]];
export const HEAP_FRAMES: string[][] = [[
    '................',
    '......oooo......',
    '....oopPPpoo....',
    '...opPPppPPpo...',
    '..opPkppppkPpo..',
    '.oppPPqppqPPppo.',
    '.oqpkppPPppkpqo.',
    'opqqpqppppqpqqpo',
    'oqqqqqqqqqqqqqqo',
    '.oooooooooooooo.',
  ], [
    '......oooo......',
    '.....opPPpo.....',
    '....opPPPPpo....',
    '...opPkppkPpo...',
    '..opPPppppPPpo..',
    '.oppPkqppqkPppo.',
    '.oqpppPPPPpppqo.',
    'opqqpqppppqpqqpo',
    'oqqqqqqqqqqqqqqo',
    '.oooooooooooooo.',
  ]];
export const LURK_FRAMES: string[][] = [[
    '......oooo......',
    '....oopPPpoo....',
    '...opPPPPPPpo...',
    '..opPkPPPPkPpo..',
    '.opPeEpkkpEePpo.',
    '.oppeepPPpeeppo.',
    'opqpppkppkpppqpo',
    'oqqktktkktktkqqo',
    '.oqqqqqqqqqqqqo.',
    '..oooooooooooo..',
    '..o.o..oo..o.o..',
    '.o..o......o..o.',
  ], [
    '......oooo......',
    '....oopPPpoo....',
    '...opPPPPPPpo...',
    '..opPkPPPPkPpo..',
    '.opPeEpkkpEePpo.',
    '.oppeepPPpeeppo.',
    'opqpppkppkpppqpo',
    'oqqktktkktktkqqo',
    '.oqqqqqqqqqqqqo.',
    '..oooooooooooo..',
    '...o.o.o.o.o....',
    '..o...o...o...o.',
  ]];
export const MILDEW_FRAMES: string[][] = [[
    '................',
    '....oooooooo....',
    '..ooCCCCCCCCoo..',
    '.oCChsCCCCshCCo.',
    'oCChCCCssCCChCCo',
    'oCsCCCCCCCCCCsCo',
    'occCCsCCCCsCCcco',
    'occcccCCCCccccco',
    '.oooooooooooooo.',
    '....oTttttTo....',
    '....oTttttTo....',
    '...oTTttttTTo...',
    '..ooTTTttTTToo..',
    '.oooooooooooooo.',
  ], [
    '....oooooooo....',
    '..ooCCCCCCCCoo..',
    '.oCChsCCCCshCCo.',
    'oCChCCCssCCChCCo',
    'oCsCCCCCCCCCCsCo',
    'oCCCCsCCCCsCCCCo',
    'occCCCCCCCCCCcco',
    'occcccCCCCccccco',
    'oggggggggggggggo',
    '.ooooTttttToooo.',
    '....oTttttTo....',
    '...oTTttttTTo...',
    '..ooTTTttTTToo..',
    '.oooooooooooooo.',
  ]];
export const KEEPER_FRAMES: string[][] = [[
    '....ooo.....',
    '...oCCCo....',
    '..oChCCCo...',
    '..oCkkkCo...',
    '..okekekoo..',
    '..oCCCCCo...',
    '.oCChCCCCo..',
    '.oCCCCCCCooo',
    '.oCCCCCCo.o.',
    '.ocCCCCCooLo',
    '.ocCCCCCoLyL',
    '.occCCCCooLo',
    '.occcCCCo.o.',
    '..occcCCo...',
    '..occccco...',
    '..ooooooo...',
    '...o..o.....',
    '............',
  ], [
    '............',
    '....ooo.....',
    '...oCCCo....',
    '..oChCCCo...',
    '..oCkkkCo...',
    '..okekekoo..',
    '..oCCCCCo...',
    '.oCChCCCCo..',
    '.oCCCCCCCooo',
    '.oCCCCCCo.o.',
    '.ocCCCCCooLo',
    '.ocCCCCCoLyL',
    '.occCCCCooLo',
    '.occcCCCo.o.',
    '..occcCCo...',
    '..occccco...',
    '..ooooooo...',
    '....o.o.....',
  ]];

/** For the sprite preview tool. */
export function sheet(): Record<string, { rows: string[]; pal: Palette }> {
  const s: Record<string, { rows: string[]; pal: Palette }> = {};
  ([['trunk', TRUNK_FRAMES, TRUNK_PAL], ['heap', HEAP_FRAMES, LURK_PAL], ['lurk', LURK_FRAMES, LURK_PAL], ['mildew', MILDEW_FRAMES, MILDEW_PAL], ['keeper', KEEPER_FRAMES, KEEPER_PAL]] as [string, string[][], Palette][])
    .forEach(([n, fr, pal]) => fr.forEach((rows, i) => { s[n + i] = { rows, pal }; }));
  return s;
}
