#!/usr/bin/env python3
"""Pack the chapter MIDI files (assets/music/midi) into src/audio/chapterdata.ts.

Each MIDI has the same five parts: drums, bass, harmony, lead and detail. Notes are stored per part
as base64 varints (start delta and length in 1/96ths of a beat, then pitch and velocity), which keeps
the players' small timing pushes and pulls while staying a fraction of the MIDI size.

Usage: python3 scripts/midi2chapters.py
"""
import base64, csv, glob, json, os, struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UNIT = 96  # steps per beat


def vlq(d, i):
    v = 0
    while True:
        b = d[i]; i += 1; v = (v << 7) | (b & 0x7f)
        if not b & 0x80:
            return v, i


def parse(path):
    d = open(path, 'rb').read()
    assert d[:4] == b'MThd', path
    _fmt, ntrk, div = struct.unpack('>HHH', d[8:14])
    i = 8 + struct.unpack('>I', d[4:8])[0]
    tempo, meter, notes = None, (4, 4), []
    for _ in range(ntrk):
        assert d[i:i + 4] == b'MTrk'
        ln = struct.unpack('>I', d[i + 4:i + 8])[0]; j = i + 8; end = j + ln; i = end
        tick, run, name, on = 0, None, '', {}
        while j < end:
            dt, j = vlq(d, j); tick += dt
            st = d[j]
            if st == 0xff:
                typ = d[j + 1]; l, k = vlq(d, j + 2); data = d[k:k + l]; j = k + l
                if typ == 0x51 and tempo is None: tempo = int.from_bytes(data, 'big')
                if typ == 0x58: meter = (data[0], 2 ** data[1])
                if typ == 0x03: name = data.decode('latin1')
                continue
            if st in (0xf0, 0xf7):
                l, k = vlq(d, j + 1); j = k + l; continue
            if st & 0x80: run = st; j += 1
            else: st = run
            hi, ch = st & 0xf0, st & 0x0f
            if hi in (0xc0, 0xd0): j += 1; continue
            a, b = d[j], d[j + 1]; j += 2
            if hi == 0x90 and b > 0: on[(ch, a)] = (tick, b)
            elif hi == 0x80 or (hi == 0x90 and b == 0):
                if (ch, a) in on:
                    s, v = on.pop((ch, a))
                    notes.append(('drums' if ch == 9 else name, s, tick - s, a, v))
    return div, 60e6 / (tempo or 500000), meter, notes


def varint(out, v):
    while True:
        b = v & 0x7f; v >>= 7
        out.append(b | (0x80 if v else 0))
        if not v: return


def main():
    titles = {r['chapter_id']: r['title'] for r in csv.DictReader(open(os.path.join(ROOT, 'assets/music/chapter-map.csv')))}
    songs = []
    for path in sorted(glob.glob(os.path.join(ROOT, 'assets/music/midi/*.mid'))):
        cid = os.path.basename(path)[3:-4]
        div, bpm, (num, den), notes = parse(path)
        beats_per_bar = num * 4 / den
        q = lambda t: round(t * UNIT / div)
        end = max(s + l for _, s, l, _, _ in notes) / div
        bars = -(-end // beats_per_bar) if end % beats_per_bar > 0.02 * beats_per_bar else round(end / beats_per_bar)
        parts = {}
        for role in ['drums', 'bass', 'harmony', 'lead', 'detail']:
            ns = sorted((q(s), max(1, q(l)), p, v) for r, s, l, p, v in notes if r == role)
            if not ns: continue
            out, last = bytearray(), 0
            for s, l, p, v in ns:
                varint(out, s - last); varint(out, l); out.append(p); out.append(v); last = s
            parts[role] = base64.b64encode(bytes(out)).decode()
        songs.append(dict(id=cid, title=titles.get(cid, cid), bpm=round(bpm, 3), meter=[num, den], beats=int(bars * beats_per_bar), parts=parts))
    src = ['// Generated by scripts/midi2chapters.py from assets/music/midi/*.mid. Do not edit by hand.',
           '// One song per chapter: notes per part as base64 varints (start delta and length in 1/96 beat,',
           '// then pitch and velocity).',
           'export interface ChapterTrack { id: string; title: string; bpm: number; meter: [number, number]; beats: number; parts: Partial<Record<ChapterRole, string>> }',
           "export type ChapterRole = 'drums' | 'bass' | 'harmony' | 'lead' | 'detail';",
           'export const UNIT = %d;' % UNIT,
           'export const CHAPTER_TRACKS: ChapterTrack[] = ' + json.dumps(songs, separators=(',', ':')) + ';', '']
    dst = os.path.join(ROOT, 'src/audio/chapterdata.ts')
    open(dst, 'w').write('\n'.join(src))
    print('wrote', dst, len(songs), 'songs', os.path.getsize(dst), 'bytes')


if __name__ == '__main__':
    main()
