#!/usr/bin/env python3
"""Check the chapter soundtrack and list it for the game.

The recordings live in assets/music/audio as NN-<chapter>.ogg (the build serves and copies them as
music/<chapter>.ogg). This script:
  - converts any other format dropped in there (mp3, mp4, m4a, wav, flac) to .ogg next to it,
  - checks each track's length against assets/music/chapter-map.json so it loops without a gap,
  - writes src/audio/recorded.ts, the list of chapters that have a recording.

Usage: python3 scripts/prepare-music.py
"""
import glob, json, os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIR = os.path.join(ROOT, 'assets/music/audio')
OTHER = ('.mp3', '.mp4', '.m4a', '.wav', '.flac', '.aac', '.webm', '.opus')


def samples(f):
    out = subprocess.run(['ffprobe', '-v', 'error', '-select_streams', 'a', '-show_entries', 'stream=sample_rate,duration_ts,codec_name',
                          '-of', 'json', f], capture_output=True, text=True).stdout
    s = json.loads(out)['streams'][0]
    return s['codec_name'], int(s['sample_rate']), int(s.get('duration_ts') or 0)


def main():
    meta = {}
    mp = os.path.join(ROOT, 'assets/music/chapter-map.json')
    if os.path.exists(mp):
        for c in json.load(open(mp)): meta[c['chapter_id']] = c
    for f in sorted(glob.glob(os.path.join(DIR, '*'))):
        base, ext = os.path.splitext(f)
        if ext.lower() in OTHER and not os.path.exists(base + '.ogg'):
            cid = re.sub(r'^\d+[-_ ]?', '', os.path.basename(base)).lower()
            end = meta.get(cid, {}).get('loop_end_sample')
            af = 'aresample=44100' + (f',atrim=end_sample={end},apad=whole_len={end}' if end else '')
            subprocess.run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-i', f, '-vn', '-map_metadata', '-1', '-ac', '2',
                            '-af', af, '-c:a', 'libvorbis', '-q:a', '5', base + '.ogg'], check=True)
            print('converted', os.path.basename(f))
    done = []
    for f in sorted(glob.glob(os.path.join(DIR, '*.ogg'))):
        cid = re.sub(r'^\d+[-_ ]?', '', os.path.basename(f)[:-4]).lower()
        codec, sr, n = samples(f)
        m = meta.get(cid, {})
        want = m.get('loop_end_sample')
        ok = 'ok' if want is None or n == want else f'LENGTH {n} != {want}'
        print(f'{cid:12} {codec} {sr} Hz {n / sr:7.2f}s {os.path.getsize(f) // 1024:5} KB  {ok}')
        done.append(dict(id=cid, title=m.get('title', cid), seconds=round(n / sr, 3)))
    src = ['// Generated by scripts/prepare-music.py from assets/music/audio: the chapters with a recorded theme.',
           'export interface Recording { id: string; title: string; seconds: number }',
           'export const RECORDINGS: Recording[] = [',
           *[f"  {{ id: '{d['id']}', title: {json.dumps(d['title'])}, seconds: {d['seconds']} }}," for d in done], '];', '']
    open(os.path.join(ROOT, 'src/audio/recorded.ts'), 'w').write('\n'.join(src))
    print(len(done), 'recordings')


if __name__ == '__main__':
    main()
